name: curp

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - codecov
  - numpy
  - pytorch
  - pandas
  - scikit-learn
  - matplotlib
  - opencv

variables:
  - PYTHONPATH: /home/is/Desktop/CURP/model
